artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/dataingestion
  source_URL: "https://raw.githubusercontent.com/VigneshwarKandhaiya1207/datasets/refs/heads/main/Insurance_data.csv"
  local_directory_file: artifacts/dataingestion/insurance_data.csv

data_validation:
  root_dir: artifacts/datavalidation
  source_data_location: artifacts/dataingestion/insurance_data.csv
  status_file: artifacts/datavalidation/status.txt

data_transformation:
  root_dir: artifacts/datatransformation
  source_data_location: artifacts/dataingestion/insurance_data.csv

model_trainer:
  root_dir: artifacts/modeltrainer
  train_data_path: artifacts/datatransformation/train.csv
  test_data_path: artifacts/datatransformation/test.csv
  model_name: final_model.joblib

model_evaluation:
  root_dir: artifacts/modelevaluation
  test_data_path: artifacts/datatransformation/test.csv
  model_name: artifacts/modeltrainer/final_model.joblib
  metrics_file: artifacts/modelevaluation/metrics.json


  
